/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import javax.swing.JDesktopPane;

/**
 *
 * @author melis
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
  
    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuProveedores = new javax.swing.JMenu();
        mnuMovimientos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuProveedores.setMnemonic('f');
        mnuProveedores.setText("PROVEEDORES");
        mnuProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuProveedoresMouseClicked(evt);
            }
        });
        menuBar.add(mnuProveedores);

        mnuMovimientos.setMnemonic('e');
        mnuMovimientos.setText("MOVIMIENTOS");
        mnuMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMovimientosMouseClicked(evt);
            }
        });
        menuBar.add(mnuMovimientos);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuProveedoresMouseClicked
        boolean estaAbierta = false;

        // Recorremos todas las ventanas abiertas en el panel
        for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof JIFrameProveedor) {
                estaAbierta = true;
                frame.toFront(); // Si ya existe, la trae al frente
                try {
                    frame.setSelected(true); // La selecciona físicamente
                } catch (java.beans.PropertyVetoException e) {}
                break;
            }
        }

        // Solo si no está abierta, creamos una nueva
        if (!estaAbierta) {
            JIFrameProveedor ventana = new JIFrameProveedor();
            desktopPane.add(ventana);
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_mnuProveedoresMouseClicked

    private void mnuMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMovimientosMouseClicked
        boolean estaAbierta = false;

        // Recorremos todas las ventanas abiertas en el panel
        for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof JIFrameMovimiento) {
                estaAbierta = true;
                frame.toFront(); // Si ya existe, la trae al frente
                try {
                    frame.setSelected(true); // La selecciona físicamente
                } catch (java.beans.PropertyVetoException e) {}
                break;
            }
        }

        // Solo si no está abierta, creamos una nueva
        if (!estaAbierta) {
            JIFrameMovimiento ventana = new JIFrameMovimiento();
            desktopPane.add(ventana);
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_mnuMovimientosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuMovimientos;
    private javax.swing.JMenu mnuProveedores;
    // End of variables declaration//GEN-END:variables

}
